### ISSUE TITLE
Weight for mob displayed as 0kg

### ISSUE THREAD

**Issue by jalles76** [luciensadi/AwakeMUD#1]
Not sure if it's really an issue. I created a mob (5001) with a weight of 2.00 kg. Looking at it displays the weight as 0kg.

relevant source: act.informative.cpp:500

**Comment by luciensadi** [comment]
Issue stemmed from weight guesstimation code's aggressive rounding. I've updated it so that anything <= 4 kilos "appears to barely weigh anything".
