### ISSUE TITLE
Should playergroups have the PGROUP DISBAND command available?

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#100]
The current design for playergroup commands includes the PGROUP DISBAND command, which is used by the leader to terminate the group's existence. I'm concerned that this will cause headaches for the staff without much benefit to players-- for instance, if the leader disbands the group without the agreement of the members, they're going to be upset with this and will petition to get the group restored without the faithless leader. However, the lack of a disband command wouldn't stop a determined leader from breaking the group; he or she could just kick everyone and quit the group themselves to essentially terminate it anyways. I'm interested in your thoughts on this @jalles76 (as well as anyone else who reads this); let me know what you think.

**Comment by jalles76** [comment]
I'd say leave it as it is. The founder/leader should absolutely have the power to disband a group. Players wanting to continue can fork/splinter into a new group. This makes for great RP opportunities. Maybe there could be a mechanism to claim orphaned group assets?

**Comment by luciensadi** [comment]
After some thought I agree the leader should have the capability to destroy the group (that's pretty much a given with how creative players can be with their privileges anyways), but I'm not sure how we would go about having any sort of coded way to reclaim group assets. The simple method for reclaiming assets is to ensure the set command is expanded to affect groups as well so that the staff can handle this on a case-by-case basis, but this means we're building a system that requires staff assistance. That's something I'm against as a principle, as MUD staff activity isn't something that can be relied on. However, I also don't know what an automated system would look like (who can invoke it, when, how, what are the effects, etc).

One other question-- when a group is disbanded, what should happen to their assets? I'm pretty sure leased apartments would be released back to the game, but how do we handle bank accounts, vehicles, PGHQs, etc?

**Comment by luciensadi** [comment]
Initial command implemented in 87c0690cf6896f6f893fa7b11e588496d7098de7.

Current structure is:
- Print pgroup affiliation to console for all members, including rank and privs
- Delete affiliation and invitation records for group
- Set group disabled

Still to figure out:
- How do we handle group property?
- What should we do with group log messages?
