### ISSUE TITLE
Investigate APDS ammo building

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#101]
In order to build APDS ammo, you need to hit a TN of 14. This seems excessively high. Is this intended to keep everyone in the game from having easy access to APDS ammo? Is there a different way to do this?

**Comment by jalles76** [comment]
If I remember canon correctly APDS was supposed to be rare as it was kind of OP. As we have no way of restricting crafting by rare mats for example a high TN seems to be the only way.

**Comment by luciensadi** [comment]
Yeah, I can't think of a better way to do this right now. Will keep the current system until/unless we can come up with a solid replacement.
