### ISSUE TITLE
Suggestion, map style toggle.

### ISSUE THREAD

**Issue by celtichawk** [luciensadi/AwakeMUD#107]
Not sure if this'd go under enhancement or idea, and it's getting a little bit away from the 3rd edition a bit but.....

I feel that the map needs a do over if you have either compact or screenreader toggled on. I like the map sectors, however.....with screenreader toggled on, it breaks map displaying, which is an expected result.

To that end I'll suggest this. If mapstyle is toggled on, you get the sectors listed as usual but you would get the street names displayed [like so]

For example,

read northeast

Business 1 [8th and  Gray]
Business 2 [6th and Park]

I feel it'd be a lot less clutter on the screen and make it somewhat easier to navigate around. Downsides, yeah, it'd be easier to get to plces but those same places are located on the map anyhow so it's not revealing anything that's not already marked down, it's just a simpler way of displaying the info. In fact it could possibly be put maybe into a seperate toggle if that would fit better, I'd hate for something like this to be tied to needing a screenreader mode enabled to get a different and more concise map display.

What about something like

toggle mapstyle

That would in example toggle between the grid based map and the list map styles. Same data, different way of presenting it.

**Comment by luciensadi** [comment]
I don't think the maps are even accurate anymore with the missing parts of the world, so we can definitely look at redoing those and making them a little more screenreader-friendly. They're currently implemented as items with the various directions being keywords on the item, so adding more keywords (`read index`, `read legend`, etc) is trivial but changing the map on the fly based on a toggle is very difficult.

**Comment by celtichawk** [comment]
Ah okay then what's the easiest way to clear up the map and simplify it for everyone? I doubt any of my ways I was thinking over would work given the map is an object, I was going to suggest keeping the object but retooling it into a directory format that you could browse through or search for a location by name, it'd then give you the street.

Not sure if that's workable or worth doing however.

**Comment by luciensadi** [comment]
It could work; maybe something like `read index` to give you a list of locations sorted by type, then `read <x>` to give you details on a place and its location. That's a fair amount of building work though. Would you or one of your players be willing to pull that info together (what place is where, and what's a good general / short description for these locations) so I can get that put into a screenreader-friendly version of the map?

**Comment by celtichawk** [comment]
Sure once I  start making detailed notes I'll type it up.

**Comment by luciensadi** [comment]
Planning on implementing a code-generated map that handles this stuff for us.
