### ISSUE TITLE
Enable player cyberdocs and enhance medical options

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#123]
Player characters should be able to install and uninstall 'ware (how do we handle consent?). Additional things like a medical-drug system, disease, and treatments would also be interesting.

**Comment by vitalyo7** [comment]
This was done very well in similar muds, aka Cybersphere and Hellmoo.

One of the things that can be implemented is a @trust system, where a player will not allow any other player to do anything, unless they can @trust <player> to <action>, action being heal, grab, cyberdoc etc.

Additionally, I believe we should have options to either rent clinics, or buy kits to setup in either player vehicles (trucks etc) or player owned houses and HQ.

Success of installation should be dependent on skill but capped on the facility/kit, i.e. even being a good cyberdoc but lacking the right equipment should cause penalties when installing, up to completely wasting the cybernetic part.

**Comment by luciensadi** [comment]
I like that system. The syntax wouldn't have an @ in it since that's an artifact of MOO design, but designating a list of trusted people who can modify your character is a good idea. I also like having the success of the operation capped by the facilities/tools available to the character.

Should there be any room in the system for hostile body modification? For example, shady groups that capture characters and steal their cyber/bio after knocking them out, or someone installing a spinal explosive and extorting the character into doing their dirty work. It's great RP, but I'm not sure people would be on board with it (I'd personally have a very hard time stomaching someone doing that to a character I'd spent a lot of effort building).

**Comment by luciensadi** [comment]
Implemented, player cyberdocs now exist.
