### ISSUE TITLE
Implement ALLOW X FROM Y command and related permission checks

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#137]
Create an `allow X from Y` command to grant permission to perform given actions against your character.

Example actions that require permission
- mindlink
- medical patches
- surgery

Couple with `revoke X from Y` to remove perms.

prior text:
There's no logging or anything of mindlink casts, and you can use them to spam a mundane without them having any way to stop you from doing so. This is great for RP, but bad when used for trolling.

**Comment by luciensadi** [comment]
Mindlink requires a voluntary subject, so it should be easy enough to implement a command to reject a mindlink. Perhaps a message that's sent when the mindlink is established, along with a "You may <X> to dissolve this link at any time." Will also need to have a help file, or perhaps keywords for the mindlink helpfile that include terms from the mindlink receiving text.

**Comment by luciensadi** [comment]
Maybe something like this to help identify what it is:
`You experience the telltale mental fuzz of a mindlink being formed between your thoughts and another's.`

**Comment by vitalyo7** [comment]
In another mud, there was a command, like this:

allow <action> from player.
maybe something like
allow mindlink from player?

**Comment by luciensadi** [comment]
Yeah, that'd also be a good framework for doing things like PC cybersurgery.

**Comment by vitalyo7** [comment]
also allow healing from X (mages don't like to be healed i think)
allow magic from X ( not sure if people ever complain if a spell is cast on them)
