### ISSUE TITLE
Add documentation to wiki

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#15]
The documentation in docs/staffdocs needs to be added to the wiki for easy browsing. (Thanks for writing it up for us!)

**Comment by jalles76** [comment]
Now that you mention it I know why I had some slight doubts about the markdown. For the sources it's totally sufficient to have the info in SQL. A browsable wiki makes for out-of-MUD ease of use. Eventually the info should be included in a comprehensive yet-to-be-written PDF admin guide.

**Comment by luciensadi** [comment]
Just browsed the wiki, keep up the great work! 👍
