### ISSUE TITLE
ANSI Color in Greeting

### ISSUE THREAD

**Issue by lmclarke** [luciensadi/AwakeMUD#154]
I'm admittedly still just dipping my toes in, but is there a way to enable ansi color in the greeting screen that I've missed? Is that functionality planned, if not?

**Comment by luciensadi** [comment]
Weird that that wasn't a thing. Added to master branch at 8d0d046903c01142b661743e67bee10d5ba565f1.

**Comment by lmclarke** [comment]
Fantastic. Thanks a ton.
