### ISSUE TITLE
After Advancement imms unable to view wizhelp files

### ISSUE THREAD

**Issue by lmclarke** [luciensadi/AwakeMUD#156]
Setting holylight on did not resolve. I'm betting I'm missing some setting or another. Security?

**Comment by luciensadi** [comment]
You're using the master branch, right?  I think Che's old code (the one packaged in Releases) doesn't have a functioning wizhelp. The only requirement for the wizhelp command is that you're at least level 2 (`ADVANCE SELF 2` or higher).

What's the output of the wizhelp command for you?

**Comment by lmclarke** [comment]
Wizhelp output:

>wizhelp
> The following privileged commands are available to you:
> aecho        at           award        ban          copyover     dc           
> dig          force        freeze       gaecho       gecho        goto         
> handbook     hcontrol     hedit        hlist        icedit       iclist       
> iclone       iedit        ilist        iload        imotd        incognito    
> invis        last         logwatch     mclone       medit        mlist        
> mute         muteooc      notitle      olc          oocdisable   page         
> pardon       penalize     phonelist    poofin       poofout      possess      
> purge        qlist        qedit        rclone       reboot       restore      
> rlist        rpe          redit        send         sedit        set          
> settime      skillset     slist        slowns       snowball     snoop        
> spellset     stat         subpoint     tail         teleport     thaw         
> tridlog      unban        unaffect     uptime       users        vlist        
> vnum         vset         vstat        whotitle     wtell        wf           
> wizhelp      wizlock      wwho         vedit        vteleport    zaecho       
> zecho        zedit        zlist        zreset       zswitch  

Using the master branch, yep! 

As can see wizhelp itself is fine, but when I try to access something in it:

> help set
> No such help file exists.

I used "set" because it exists in the wizhelp folder.

**Comment by luciensadi** [comment]
Ah, that's likely caused by Che's transition from the flat-file help system to the SQL help system. No provision currently exists in that system for wizhelp commands, so your best bet is going to be reading the flat files themselves. I'll keep this issue open to remind myself to add that later though.

**Comment by vitalyo7** [comment]
A few notes, the help command should be rewritten to take into account if the user is an admin or not.

Also, load command has different usage for player vs admin, which will make help for it a bit tricky. In my opinion load for admin should be moved to wizload.

**Comment by luciensadi** [comment]
Are there currently help files that should be visible to staff but not players (other than the currently-defunct wizhelps), or is this for future helpfiles?

**Comment by vitalyo7** [comment]
Is there any value of showing wizcommand help for players either in the current state or future state?

**Comment by lmclarke** [comment]
I don't think there'd be much value in that, while there may be value in obscuring it.

**Comment by luciensadi** [comment]
I can see the appeal for having a self-segregating help system. What I liked about wizhelp was the way it presented an index of files that were accessible at that level; if we move all the staff helpfiles to the main help system with level segregation, we'll have to figure out a way to let staff browse the things that they've gained access to due to their level.

**Comment by vitalyo7** [comment]
The help_topic table could get an extra column, wizlevel (default to 0) and when looking up help topics via help command, one could change the query to only show help information that is <= wizlevel of the person searching.

The remaining wizhelp commands could be added to the help_topic, with wizlevel specified. This way, the help files are only seen by those with appropriate level.

**Comment by luciensadi** [comment]
This sounds like a good plan. Also, if I'm poking at the help system again, I want to overhaul it a bit-- if there isn't an exact match to your keyword in one of the titles, it should display all the titles of matching files so you can pick what sounds closest to your request. I'm not a fan of the current "if multiples match, spam the screen with them" approach.
