### ISSUE TITLE
Crashes on copyover, possibly caused by character death

### ISSUE THREAD

**Issue by lmclarke** [luciensadi/AwakeMUD#158]
After several copyovers, the game registers the immortal character as wounded and dying, then promptly crashes. This has happened 4 times, though not in succession. I have been doing tons of copyovers while fiddling with the color scheme, but nothing else. 

**To Reproduce**
1. Copyover repeatedly, until you see"You are mortally wounded and will die soon if not aided."

**Expected behavior**
Crash.

**Current Output**
> copyover
> You are mortally wounded and will die soon if not aided.
> --- Disconnected on Sunday, October 28, 2018, 9:14 AM ---

**Additional context**
This happens only every so often, but each time it does it's when I get the notification that I'm wounded and dying. I'm unsure how an immortal pfile is incurring wounds or losing HP, and further unsure if it's a problem caused by character death or immortal character death. The former seems more likely to me.

**Comment by luciensadi** [comment]
Are you able to run the game through a debugger? A backtrace would be helpful. Depending on your OS, you can use `gdb` or `lldb`, although if you don't have either of those then I'm not sure what you could use.

Syntax for gdb/lldb:
`[gdb|lldb] bin/awake` `run` (wait for a crash) `bt`. Whenever you copyover in-game you'll have to `continue` in gdb/lldb.

**Comment by lmclarke** [comment]
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib64/libthread_db.so.1".
> Oct 28 09:33:49 :: Using lib as data directory.
> Oct 28 09:33:49 :: Running game on port 9996.
> Oct 28 09:33:49 :: Setting player limit to 300 using rlimit.
> Oct 28 09:33:49 :: DBInit -- BEGIN.
> Oct 28 09:33:49 :: Resetting the game time:
> Oct 28 09:33:49 ::    Current Gametime: 2/23/2064 4:00.
> Oct 28 09:33:49 :: Reading news, credits, help, bground, info & motds.
> Oct 28 09:33:49 :: Loading fight messages.
> Oct 28 09:33:49 :: Booting World.
> Oct 28 09:33:49 :: Booting MYSQL database.
> Oct 28 09:33:49 :: Handling idle deletion.
> Oct 28 09:33:49 :: Executing query: SELECT idnum FROM pfiles WHERE lastd <= 1536                                 424429 AND nodelete = 0 ORDER BY lastd ASC;
> Oct 28 09:33:49 :: IDLEDELETE- 0 Deleted.
> Oct 28 09:33:49 :: Loading zone table.
> Oct 28 09:33:49 :: Loading rooms.
> Oct 28 09:33:50 :: Checking start rooms.
> Oct 28 09:33:50 :: Loading mobs and generating index.
> Oct 28 09:33:50 :: Loading objs and generating index.
> Oct 28 09:33:50 :: Loading vehicles and generating index.
> Oct 28 09:33:50 :: Loading quests.
> Oct 28 09:33:50 :: Loading shops.
> Oct 28 09:33:50 :: Loading Matrix Hosts.
> Sun Oct 28 09:33:50 :: SYSLOG: Unable to find file world/mtx/0.host.
> Sun Oct 28 09:33:50 :: SYSLOG: Unable to find file world/mtx/6.host.
> Sun Oct 28 09:33:50 :: SYSLOG: Unable to find file world/mtx/11.host.
> Sun Oct 28 09:33:50 :: SYSLOG: Unable to find file world/mtx/100.host.
> Sun Oct 28 09:33:50 :: SYSLOG: Unable to find file world/mtx/171.host.
> Oct 28 09:33:50 :: SYSERR: boot error - 0 records counted
> [Inferior 1 (process 708) exited with code 01]
> Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-23.el7                                 .x86_64 glibc-2.17-222.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.1                                 5.1-19.el7.x86_64 libcom_err-1.42.9-12.el7_5.x86_64 libcurl-7.29.0-46.el7.x86_64                                  libgcc-4.8.5-28.el7_5.1.x86_64 libidn-1.28-4.el7.x86_64 libselinux-2.5-12.el7.x                                 86_64 libssh2-1.4.3-10.el7_2.1.x86_64 libstdc++-4.8.5-28.el7_5.1.x86_64 nspr-4.1                                 9.0-1.el7_5.x86_64 nss-3.36.0-7.el7_5.x86_64 nss-softokn-freebl-3.36.0-5.el7_5.x                                 86_64 nss-util-3.36.0-1.el7_5.x86_64 openldap-2.4.44-15.el7_5.x86_64 openssl-lib                                 s-1.0.2k-12.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-17.el7.x86_64
> (gdb) bt
> No stack.

**Comment by luciensadi** [comment]
Looks like it's got the wrong invocation. How do you usually start the game, and from which directory relative the the base directory?

**Comment by luciensadi** [comment]
Also it looks like it wants you to install some extra debug packages, you should run that command it advises in the "Missing separate debuginfos" line.

**Comment by lmclarke** [comment]
I usually start the game from the base directory using the autorun script - ./autorun.

**Comment by luciensadi** [comment]
OK, I was able to reproduce the bug. My guess right now is that it's the game exhausting some system resource (descriptors maybe?) and failing to obtain more. I'll look into it, but this one will take a while to track down.

Corroborating log:
```Oct 28 12:39:58 :: Using lib as data directory.
Oct 28 12:39:58 :: Running game on port 4000.
Oct 28 12:39:58 :: Setting player limit to 300 using rlimit.
Oct 28 12:39:58 :: DBInit -- BEGIN.
Oct 28 12:39:58 :: Resetting the game time:
Oct 28 12:39:58 ::    Current Gametime: 2/19/2064 7:00.
Oct 28 12:39:58 :: Reading news, credits, help, bground, info & motds.
Oct 28 12:39:58 :: Loading fight messages.
Oct 28 12:39:58 :: Booting World.
Oct 28 12:39:58 :: Booting MYSQL database.
Oct 28 12:39:58 :: Handling idle deletion.
Oct 28 12:39:58 :: Executing query: SELECT idnum FROM pfiles WHERE lastd <= 1536435598 AND nodelete = 0 ORDER BY lastd ASC;
Oct 28 12:39:58 :: IDLEDELETE- 0 Deleted.
Oct 28 12:39:58 :: Loading zone table.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/0.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/3.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/5.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/6.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/7.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/10.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/11.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/13.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/18.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/20.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/50.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/74.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/99.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/100.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/101.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/171.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/325.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/355.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/605.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/700.zon.
Sun Oct 28 12:39:58 :: SYSLOG: Unable to find file world/zon/701.zon.
Oct 28 12:39:58 :: SYSERR: boot error - 0 records counted```

**Comment by luciensadi** [comment]
The game will still crash if you copyover something like 250+ times, since every copyover keeps a file descriptor open from the previous version of the game calling the new one. I've cut down some of the file descriptor leakage though, so the copyovers-until-crash figure is much larger now.
