### ISSUE TITLE
Slowing Down MUD Time

### ISSUE THREAD

**Issue by lmclarke** [luciensadi/AwakeMUD#166]
**Slowing down MUD time**
I'm attempting to slow MUD time down to about 1/3 of RL time, rather than what it is now. Ideally, one in-game hour would pass every 20 minutes in real time.

I changed this:
```
/* mud-life time */
#define SECS_PER_MUD_MINUTE 2
```

To:
```
/* mud-life time */
#define SECS_PER_MUD_MINUTE 20
```

But I'm unsure if that was the right thing to change. It doesn't appear to have made an impact. What should I be editing to adjust this?

**Comment by luciensadi** [comment]
It's a bit finicky. It's possible to slow down MUD time, but what are you looking to accomplish with that-- just the clock and shops being slower, or do you want all actions (combat, healing, etc) to be slower as well?

**Comment by lmclarke** [comment]
Hmm. Only MUD time. I have a feeling fiddling with the timers on combat and won't be a good idea until I've gotten a better handle on things - even then, they seem good now!

**Comment by lmclarke** [comment]
Thank you for pointing me in the right direction. I think I'll dig into it.
