### ISSUE TITLE
poofin/poofout message gets set to (null) when called with no argument

### ISSUE THREAD

**Issue by jalles76** [luciensadi/AwakeMUD#17]
Circle's wizhelp guide states on page 5-6:

Sets the message seen by players when you use GOTO to move to a different
room. POOFIN with no argument resets your poofin to the default "appears with
an ear-splitting bang"; POOFOUT with no argument defaults to "disappears in
a puff of smoke."

However, Awake does not set a default message for both commands if called without arguments.

As (null) is not a nice thing for a player to see this should be changed.

**Comment by luciensadi** [comment]
Looks like the current implementation displays your poofin / poofout.

> > poofin
> Your current poofin is: Lucien appears in a flash of light.

This may be an issue related to your SQL DB-- for a while there were no defaults set, so you could end up with a null poofin. A change a few weeks ago set defaults so all new immortals will have the following poofins / poofouts until changed:

```
CREATE TABLE `pfiles_immortdata` ( 
  `idnum` mediumint(5) unsigned unique default '0', 
  `InvisLevel` tinyint(1) default '0', 
  `IncogLevel` tinyint(1) default '0', 
  `Zonenumber` mediumint(3) default '1', 
  `PoofIn` varchar(200) default 'Someone appears from nowhere.', 
  `PoofOut` varchar(200) default 'You blink and someone is gone.', 
  PRIMARY KEY (`idnum`) 
);
```

**Comment by jalles76** [comment]
Strange. I started over with a blank/new DB and the president's table still looks like this:

``
mysql> select * from pfiles_immortdata\G;
*************************** 1. row ***************************
     idnum: 1
InvisLevel: 0
IncogLevel: 0
Zonenumber: 0
    PoofIn: (null)
   PoofOut: (null)
1 row in set (0.00 sec)
``

Despite the default value being correct:

``
mysql> desc pfiles_immortdata;
+------------+-----------------------+------+-----+-------------------------------+-------+
| Field      | Type                  | Null | Key | Default                       | Extra |
+------------+-----------------------+------+-----+-------------------------------+-------+
| idnum      | mediumint(5) unsigned | NO   | PRI | 0                             |       |
| InvisLevel | tinyint(1)            | YES  |     | 0                             |       |
| IncogLevel | tinyint(1)            | YES  |     | 0                             |       |
| Zonenumber | mediumint(3)          | YES  |     | 1                             |       |
| PoofIn     | varchar(200)          | YES  |     | Someone appears from nowhere  |       |
| PoofOut    | varchar(200)          | YES  |     | You blink and someone is gone |       |
+------------+-----------------------+------+-----+-------------------------------+-------+
6 rows in set (0.00 sec)
``

**Comment by luciensadi** [comment]
Hm, it may be caused by init_char_sql (chargen.cpp line 545) inserting poofin/poofout values even when the imm couldn't have set them yet. Worth looking into.

**Comment by luciensadi** [comment]
TODO: When a null is read back from mysql, does it display as '' or '(null)'? If the latter, a slight rewrite of the load_char method is needed to accommodate.

**Comment by jalles76** [comment]
It does indeed return '(null)'

**Comment by luciensadi** [comment]
Alright, fixed the null string comparison in https://github.com/luciensadi/AwakeMUD/commit/70e464e28bc017f64ed55b9f9953b3153510144c. This issue should be fixed now.

**Comment by jalles76** [comment]
Fix confirmed!
