### ISSUE TITLE
A CHANGES command to show what's new in the game.

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#181]
**Is your feature request related to a problem? Please describe.**
It's not always easy to tell what's changed about the game. Updating the MOTD can help with this, but that's not always done, and past changes fall off.

**Describe the solution you'd like**
An in-game way to reference changes to the MUD that keeps history would be good to have.

**Additional context**
Bug City previously had a hacky solution where `changes` functioned like the immortal `at` command, but would transfer you to a specific board, have you list it, and transfer you back. This probably isn't an ideal fix (how does it handle deckers? riggers?).

**Comment by lmclarke** [comment]
Here's how it's accomplished on ROM (I think it's 2.4), which could be a decent starting point for the "how":
http://www.mudbytes.net/files/view/2426/

**Comment by luciensadi** [comment]
Thanks for the link @lmclarke. Drawing some inspiration from that, this is a potential design for this feature:

*Syntax:*
`changes`: Displays a list of the X most recent change summaries.
`changes X`: Displays the details for change X.
`changes list X Y` Displays a list of change summaries from index X to Y.
`changes all`: Displays a paginated list of all change summaries from the most recent to least.
`changes add`: Enters an OLC-style editor for a new change entry.
`changes edit X`: Enters an OLC-style editor for an existing change entry.
`changes delete X`: Removes an existing change entry.

Changes would be stored in a new DB table, tracking an index number, a summary (a short blurb about the change, ex: "Added PROBE command for viewing OOC stats"), a description (a longer blurb with all the relevant info), the change's author idnum, and a deleted flag.

**Comment by vitalyo7** [comment]
On LambaMoo style muds, like HellMoo, this was done by ingame message boards, when you connect you would see something like.

5 new messages on clip (change log public)
2 new messages in other board.

You could type next clp, which would read the next message from the last one you read.

You can have multiple boards, similar to forums but they use the same commands to read/write/skip messages.

**Comment by luciensadi** [comment]
At this point, the Discord #changelog channel is our go-to for change info. Adding an in-game version is low on the priority list, so I'll close this for now.
