### ISSUE TITLE
ZEditor ID Numbers Don't Save

### ISSUE THREAD

**Issue by lmclarke** [luciensadi/AwakeMUD#186]
**ZEditor ID Numbers Don't Save**
When inside the zedit OLC, choosing option 7 and entering the builder's IDnum doesn't print or save.

**To Reproduce**
> zswitch # 
> zedit
> 7
> <your ID number here>

**Expected behavior**
The line for "Editor's ID Numbers:" will still have 0's across the board.

**Current Output**
```
Zone: 15
1) Name: San Angeles South
2) Top of zone: 1700
3) Lifespan: 100
4) Reset mode: Reset if no PCs are in zone
5) Security level: 2
6) Jurisdiction: South San Angeles
7) Editor's ID Numbers: 0, 0, 0, 0, 0
8) Connected: 0
q) Quit
Enter selection: 
7
Enter ID list separated by spaces:
2
Zone: 15
1) Name: San Angeles South
2) Top of zone: 1700
3) Lifespan: 100
4) Reset mode: Reset if no PCs are in zone
5) Security level: 2
6) Jurisdiction: South San Angeles
7) Editor's ID Numbers: 0, 0, 0, 0, 0
8) Connected: 0
q) Quit
Enter selection: 
```

To confirm my IDnum:
` ID NUM: 2  `

**Comment by luciensadi** [comment]
This is a syntax problem compounded by a lack of error messaging. If you enter `2 0 0 0 0` it will work, but otherwise it will silently fail. Resolution for this issue will require expanded error messaging and a smarter syntax that automatically fills in 0's for missing fields.

**Comment by luciensadi** [comment]
Added expanded error messaging. Will recategorize as an enhancement / feature fix for the parser changes.
