### ISSUE TITLE
Remove all old magazines (anything like 'a X-round Y magazine')

### ISSUE THREAD

**Issue by vitalyo7** [luciensadi/AwakeMUD#195]
Some clips have Val1 (weapon type) set to values above maximum, ie 25 when maximum is 22. This impacts smg guns in particular. I was trying to find a clip for ingram smartgun, and was surprised that I could not load an smg clip with correct capacity. Further looking at the clip via iedit, i noticed that smg clip had 25 as weapon type set, instead of expected 10 (smg).

My assumption is that the zones/obj/mobs etc in this codebase are older. And at some point Che's code had more weapon types introduced, which explains why the clips have such high values, but the old weapons, do not.

**Comment by luciensadi** [comment]
Yeah, a lot of the codebase is straddling the ammo-fix divide. Che overhauled weapons so that they use modular magazines, so all prior magazines are likely broken and should just be removed.
