### ISSUE TITLE
Random connections from the internet stay open forever on Get Name state

### ISSUE THREAD

**Issue by johnathansult** [luciensadi/AwakeMUD#196]
**Is your feature request related to a problem? Please describe.**
If your game is exposed to the Internet in a known address space like AWS, port scanners appear to connect to the game and just hang on 'Get name' state in the USERS info screen.

**Describe the solution you'd like**
Users who don't enter their name in a given amount of time should be disconnected.

**Additional context**
```
users
Num  Name           State           Idle Login@   Site
---- -------------- --------------- ---- -------- ---------------------------
488  Gen            Playing            0 22:03:43 [redacted]
373  UNDEFINED      Get name             20:44:42 [abts-tn-static-075.149.165.122.airtelbroadband
.in]
144  UNDEFINED      Get name             14:07:15 [cable190-249-128-182.epm.net.co]
```

**Comment by luciensadi** [comment]
A disconnection routine for idlers existed already, but was bugged and not fully implemented.
