### ISSUE TITLE
Vehicles cannot be individually purged

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#20]
The only way I've found to purge vehicles is to purge the whole room, which is unappealing for a variety of reasons. The purge command should be expanded to allow targeting of vehicles.

**Comment by jalles76** [comment]
That's interesting. When I started playing on AW again I rented a garage with two vehicles in it from the previous tenant. I asked an imm to remove them. When I logged back in they were gone. I assume the imm in question picked up all my equipment present in the room before purging. Cumbersome.
