### ISSUE TITLE
Enhancements to PURGE

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#204]
PURGE on its own wipes out a whole room's contents with no record of what was destroyed. Some enhancements should be made:

- Log everything that `purge` destroys so that it can be recreated if necessary.
- Require the full `purge` command be typed (similar to `quit`).
- ~~Revisit `purge` to ensure it handles all nested things correctly (see #139 for details).~~

Does it need any other tweaks?

**Comment by vitalyo7** [comment]
I haven't looked closely into how deletion works. But one mechanism that I saw in other MOO was that there was dedicated room, "furnance" where objects got moved to be deleted. Furthermore, all objects were not deleted at once, but every tick, if that room had any objects, they would be deleted.

We could implement something similar. define the room in 0 zone as a purge room. When doing a purge on any (object/vehicle/item/etc).

on Purge tick:
   count x objects to be purged
   If they object is a container, move its contents to purge room.
   If object is not valid for purge -> active/sleeping player/house etc -> move it somewhere safe, log it.
   If the object is an empty container, or non-container object, log it, "delete it"

This will have a benefit of not causing a lag spike during purge, properly emptying items from containers and we can log items being purged, as well as safely move items that should not be purged.

**Comment by luciensadi** [comment]
Purge doesn't cause lag at the moment; I just did a purge of 300+ objects, 10 vehicles, and a few NPCs, and it executed in 2/10ths of a second.

What would you define as an item that should not be purged?

**Comment by vitalyo7** [comment]
Players and player vehicles, things that are currently in used by players. I.e. purging a deck while a player is using it. Basically an item that will cause a crash/unpredictable behavior if purged.

What currently happens if you purge an object the player is using like an deck/vehicle/puppeted npc?

**Comment by luciensadi** [comment]
Not sure, if you want to test and see how many ways you can crash the MUD I'm all for that :D

**Comment by luciensadi** [comment]
Purge logging works well, but we don't have checking for things that would crash the game. However, we also haven't crashed from purging, so let's deal with them on a case by case basis when they come up.
