### ISSUE TITLE
Remove all NERP skills and items from Chargen, or put them in a special NERP area

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#211]
**Is your feature request related to a problem? Please describe.**
Newbies can be easily frustrated by buying non-implemented items, cyber, gear, skills, spells, etc.

**Describe the solution you'd like**
Either relocate all these NERP things to a specific area of non-implemented things in Chargen, or remove them entirely.

**Comment by vitalyo7** [comment]
The codebase should be purged from the non functional code an items, however all the previous code/world data should go into a newly created folder, for IDEAs, to keep things that were designed but not fully implemented. In case someone in the future decides to ever implement it. Similarly new ideas that are worth considering should go there as well.

**Comment by luciensadi** [comment]
IIRC the NERP skills and items were there so people could buy them and use them on player/staff runs. They're super-simple placeholders in code, so not worth saving in and of themselves. I do like the idea of saving snippets though! I've been sticking dead code I find in the `snippets/` folder in the root directory.

Personally, I don't mind keeping NERP skills so people can keep advancing their characters after they hit coded endgame, but I do think they need to be made difficult to access in Chargen so newbies don't get confused by them.

**Comment by luciensadi** [comment]
All NERP skills are now at the swirling mass.
