### ISSUE TITLE
Adjusting taxis

### ISSUE THREAD

**Issue by celtichawk** [luciensadi/AwakeMUD#217]
I'm back again since I've been keeping up with this fork. Something I wanted to suggest was this, since it just happened.

Taxis, currently, you type hail and it shows up in a random direction. I'd like to suggest instead it creats a dedicated 'taxi' exit. For instance, if I'm outside of the airport, and I do hail, and get a taxi, it'd show taxi on the exits list, so rather than having a message about the doors opening to the (whatever direction) then being told You cannot go that way.... you could just type taxi and enter the taxi.

**Comment by luciensadi** [comment]
Good idea, certainly doable with the current setup. I'd have to look into the code to see what the best way to implement this would be, but off the top of my head it'd be a command that scans the exits of the room you're in and looks for one pointing to a taxi's vnum, then moves you there if it finds one.
