### ISSUE TITLE
Add timeouts for punitive commands

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#23]
Commands such as 'mute', 'freeze', etc do not have any timeouts and are set-and-forget commands. Contesting or appealing these commands is difficult, especially if the staffer who set them is not present or has left the game. Forcing the staffer to set a maximum timeout on these commands ensures that problem players have a chance to mend their ways.

Rough design:
`freeze <character> <minutes>`
if minutes > 1 d * 24 h/d * 60 m/h (one day), display caution message (ex: "Freezing players for too long can provoke further antisocial behavior. Are you sure you want to continue?")
if minutes > arbitrary maximum, display error message and return.

The above will need discussion and calibration before it's designed into the code, and the timeout thresholds will need to be configurable on a per-codebase level.

**Comment by jalles76** [comment]
Good thinking. Or a default of, say, 1 day could be set with the option for the staffer to set a custom time period. Imms could also get a daily digest mailed to them via mudmail.

**Comment by jalles76** [comment]
Or, if a staffer logs on they're shown all active punitive actions with timestamp, staff member and a reason (which would have to be supplied along with the command)

**Comment by luciensadi** [comment]
I'm thinking a daily digest via mudmail plus a command to review current punishments is a good place for us to be; there's a fine line between providing the info the staff needs to do their job and annoying them that we don't want to cross.

**Comment by jalles76** [comment]
Or make it fully optional (i.e. ability to opt out of the mudmail).

**Comment by luciensadi** [comment]
I like that. So, to recap:

- punitive commands have a default length (1 hour?) which can be overridden
- there is a warning threshold (1 day?) where the imm gets a message advising against setting it too long
- there is an error threshold (1 week?) where the command is rejected
- imms are given a digest mudmail every day telling them about the current punitives, they can opt opt
- imms can execute a command to view current punitives and their time remaining

Also, we need to ensure that unfreeze etc can be performed against a file / non-loaded player.

**Comment by jalles76** [comment]
That about sums it up, yes. I don't think there's anything missing.
