### ISSUE TITLE
Add an 'authorize' command, or revisit messaging for 'set x auth off'.

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#24]
It's hard to tell what the effect of 'set x auth on/off' is; it controls the authorize flag, but unless you know what the authorize flag does, you may think that setting it to on authorizes the character fully. We should either add an authorize command or better messaging to the set command to clarify this use case.

**Comment by jalles76** [comment]
Indeed. I ran into that trap myself.
