### ISSUE TITLE
branch playergroups does not compile

### ISSUE THREAD

**Issue by jalles76** [luciensadi/AwakeMUD#25]
Not sure whether I should open an issue for an unmerged branch but I think I'm missing something here.
gcc 4.8.4 on Ubuntu 14.04

g++  -DDEBUG -DSELFADVANCE -Dlinux -Wall -I /usr/local/include/ -ggdb  -c -o playergroup_classes.o playergroup_classes.cpp
playergroup_classes.cpp: In member function ‘void Playergroup::audit_log_vfprintf(const char*, ...)’:
playergroup_classes.cpp:215:24: error: ‘va_start’ was not declared in this scope
   va_start(args, format);
                        ^
playergroup_classes.cpp:217:14: error: ‘va_end’ was not declared in this scope
   va_end(args);
              ^
make: *** [playergroup_classes.o] Error 1

**Comment by luciensadi** [comment]
https://pbs.twimg.com/profile_images/2727748211/c3d0981ae770f926eedf4eda7505b006.jpeg

**Comment by luciensadi** [comment]
Looks like the issue was a missing stdarg.h include, which is strange because it compiled on my machine. Cross-platform gremlins at work.
