### ISSUE TITLE
Prevent characters from leasing more than one room in a given apartment complex.

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#253]
Making this change means that rooms will map to characters on a 1:1 basis within a complex and we won't have to worry about anyone claiming multiple rooms just so they can sort their mountains of crap better.

**Comment by vitalyo7** [comment]
Not sure about this, a) having more apartments is a good economy sink, b) shadowrunners need safehouses.

The only change that I think should be is how many apartments/safehouses players should be able to have, i,e cannot rent every single room, but have a limit based on their IC need.

If there is an ever perk system that will get implemented, maybe this could be a perk/resource/connection thing. I.e. if the player has a contact that allows them to store gear in case things go really bad, or player has a perk that makes them paranoid and have a need for extra safehouses.

**Comment by luciensadi** [comment]
Limiting to one room per apartment complex means that you can have multiple safehouses across the city, but not in the same building. It helps force players towards the more expensive buildings instead of having them opt to rent out multiple rooms in the cheapest building, which crowds out newbies.

Also, the concept of apartments being 100% safe should be revisited; so much completely-untouchable secret RP goes on in those rooms where other players can't eavesdrop as astrals etc or come after them to further a plot.
