### ISSUE TITLE
Implement write command

### ISSUE THREAD

**Issue by jalles76** [luciensadi/AwakeMUD#26]
For RP purposes players should be able to record messages using pen and paper.

Precondition: have an object with a PEN flag and an object with WRITEBAL in inventory.

Restrictions: length

Could use a dumbed down implementation of iedit. Abuse possible?

**Comment by luciensadi** [comment]
This functionality is partially covered by both custom cyberdeck creation and pocket secretary note-taking. However, I can see the argument for having a physical, codedly-kosher note item, so I'll keep this issue open.
