### ISSUE TITLE
Adept power Improved Ability

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#277]
Improved Ability (SR3 p169) is not currently implemented. Need to look into why this is the case and implement it if there's no good reason to leave it out.

**Comment by UndeadNappist** [comment]
Having +skill points in skills in a way that nobody else has access to, particularly when the game focuses around balancing around those fixed skills by leveraging target numbers (where the probability swings become more severe the more dice you have) creates a severe destabilizing effect.

I will also note here that for many adept abilities (with exceptions) they're canonically anchored to the magic rating of the adept, not a fixed number, which isn't great for game balance either.
