### ISSUE TITLE
Some modes for 'show' are unimplemented

### ISSUE THREAD

**Issue by jalles76** [luciensadi/AwakeMUD#29]
The following modes for the 'show' command are unimplemented (act.wizard.cpp):

library
lodge
rent

This is informational only. It should be discussed whether these modes should be implemented or removed.

**Comment by luciensadi** [comment]
Any idea what they should do?

**Comment by jalles76** [comment]
I guess they are intended to list rooms with libraries/lodges. Possibly library and lodge were thought to be room flags at some point (nice idea, if you think about it).

rent [player] could show rent/load rooms for any or a single player along with the room title.
