### ISSUE TITLE
Door perception check is spammable, which makes it pointless

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#310]
You can just spam `LOOK <dir>` as many times as you want in quick succession to get that many perception tests against whatever exit is in that direction. This should be fixed so you get one test per time period X.

**Comment by vitalyo7** [comment]
What exactly are the perception test for, to find hidden exits or other things? If it is for hidden exits, maybe we can implement a search command instead (with timers), and leave look command for things the player already can see.

**Comment by luciensadi** [comment]
Perception is used all over the game for things like seeing more about a character's equipment, looking at a moving vehicle, finding hidden exits, noticing people casting magic, etc.

A search command would work well for exits and hidden things.
