### ISSUE TITLE
Add a RECALL or STUCK command to let solo players get out of pits etc.

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#318]
If you're the only person on and you get stuck at the bottom of a pit or behind a resetting door you don't have the key to, your choices are either suicide or logging off and not playing for hours until you automatically reset to your home room. A command should be added to allow people to warp home.

- Command should not be usable within X minutes of combat or taking damage.
- Command should take time to invoke (10 seconds?).
- Command should be logged to wiz channels so abuse can be investigated.

Should command be announced to other players too so they can more easily detect if someone is abusing it during a PK / PVP situation?

**Comment by luciensadi** [comment]
Updated thoughts on this:
- You cannot use the command until it's been 1 minute since you've taken damage from an NPC, or 5 minutes since you've taken damage from a player (this latter part only happens if you're killer/PK and/or blacklisted(?)).
- Invoking a command sends a message to the room, allowing any player in the room to stop the recall with a command of their own within the next ~5 seconds.
- Performing any action stops the recall.
- A successful recall is announced to imms, and also logged to a player-accessible channel (OOC? a new channel?) for auditing and accountability.
- Recalling places you at Dante's or another public place-- no recalling to absolute safety like an apartment.

Also, sufficiently-new characters (under 26 TKE? 100?) have the following easing of restrictions:
- The NPC damage time restriction does not apply. As long as you're not in combat with an NPC, their damage won't prevent recall, even if you just fled from an aggro mob.

**Comment by UndeadNappist** [comment]
Use a RETRACE command instead, that automatically takes you to the room you were previously in (or checks to see what rooms dump into the one you're stuck in and puts you there). Less abusive and just takes you one step back.
