### ISSUE TITLE
Bonded magazines need to lose their bonded keyword.

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#329]
```
bond blank ak
You bond a new magazine to an AK-97 assault rifle.

bond blank ak
<10P 10M> That magazine's already been bonded to something else.

bond blank ak
<10P 10M> That magazine's already been bonded to something else.
```

**Comment by vitalyo7** [comment]
What is the purpose of the whole bonding mechanic? Is this to avoid people searching for proper clips for their guns? Should we just replace the whole bonding mechanic by universal clips. No need to bond, just carry a generic "ammo" that has number of rounds contained.

**Comment by luciensadi** [comment]
Yeah, it was an effort to make it so builders didn't need to make a new mag for every gun/ammo combination. I originally wrote a snippet for it (http://www.awakenedworlds.net/boards/viewtopic.php?p=8830#8830), but Che discarded that system and rewrote it.

I'm not sure I want to get rid of magazines entirely; it's a resource management system that means players must either choose to load their pockets with magazines or save room for other things (radios, phones, etc). However, I could see getting rid of buying/bonding magazines and replacing it with a system where you use a gun on an ammo box to spawn the correct, loaded magazine from that box. You'd definitely have to be out of combat to do it, and maybe there'd be a short delay imposed on your character when doing it to make the player feel vulnerable / discourage doing it in a combat zone.

With the above system, we could purge the empty magazines when the character reloads-- something like this:

> *Click*
> You reload an AK-97 assault rifle and pocket the empty mag.

This system of purging empty magazines would lose the flavor of a pile of empty magazines in a room from a drawn-out fight, but gun clutter could be added to rooms like blood to fix this. It'd certainly help simplify things and would probably lead to a better newbie experience.

**Comment by vitalyo7** [comment]
I liked the magazine system, maybe we can "cheat a bit" by making universal magazine but only limited to a weapon type. I.e. rifle magazine, that fits all rifle. A pistol that fits all pistols. Also make ammo kiosks where players can purchase ammo, available in a good number of locations, so players can refill most common type of ammo easily.

Also we should remove the logic that counts bullets in each clip. A reload would fill the weapon to max capacity and discard the clip completely. No need to check how much ammo is available in the clip. etc.

Exotic ammo like gel clips would still need to be purchased from a shop.

**Comment by luciensadi** [comment]
Drew up an ammo overhaul system that uses a lot of ideas from above. Let me know what you think.
