### ISSUE TITLE
Change condition messages for inanimate NPCs

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#334]
Drones don't get "mortally wounded" and can't be "bleeding from awfully big wounds and unconscious". Update this to:

> A cobbled-together JunkBot-3 security drone is lying here, critically damaged.

> Expertly welded together from the parts of ten different commercial drones,
> this amalgamation of technology trundles around the entrance to the Junkyard,
> intimidating trespassers and the occasional stray dog as they approach the
> chain-link gate. 
> It looks to be about 1.5 meters tall and appears to weigh about 300 kg.
> A cobbled-together JunkBot-3 security drone is nearly destroyed and has shut down.

**Comment by luciensadi** [comment]
Also make sure health-category spells and adept abilities don't work on inanimate NPCs.

**Comment by vitalyo7** [comment]
I recommend that we have some way to implement static properties for objects that have the same vnum, rather than individual mobile properties.

we could add static properties like:
mob.static.type = TYPE_BIOLOGICAL | TYPE_MECHANICAL
mob.static.blood_type = BLOOD_RED | BLOOD_SYNTHETIC_FLUID | BLOOD_BUG_SPLATTER (for critters maybe) | BLOOD_ASTRAL | BLOOD_MATRIX (shatters into digital bits)

that way npcs could have a different blood when "bleeding"

**Comment by vitalyo7** [comment]
shooting bots would then result in them leacking mechanical fluid and sparks.

**Comment by luciensadi** [comment]
I'm not sure what you mean by individual mobile properties; inanimate is a flag that's applied to NPCs during mob editing, so it applies to all NPCs of that vnum. Adding different blood types would be interesting flavor, but you'd have to figure out how to represent it in the room when there's a lot of blood there.

**Comment by vitalyo7** [comment]
This is the implementation in Hellmoo that handles this thing pretty well:

We could remove the blood property from the room, etc. And instead create another type of ITEM called decal, which would represent extra visual elements on objects. For example room that has blood stains, blood stains being a decal.

Things like blood, bullet halls, aura traces, smoke, tire tracks, dna traces would be decals that get spawned during combat. These decals would eventually expire, but while they exist they would be contained on the room (or item/vehicle/mobile). You could walk into the room, after combat and it would have added description from decals, similar.

You see a bar. (decals added) You see a pool of blood on the floor. There are traces of mechanical fluid. The room is covered in a layer of smoke, making it harder to see.

The decals would show up differently when you do look command. Meaning they would not show up as items on the floor, but rather added to the description of the object.

I forget how the ice sheet spell works currently, but ice sheet could be a decal as well that gets applied to the room when the spell is cast. Some of the combat rule could check which decals are present to see if they negatively impact any tests.

**Comment by luciensadi** [comment]
Interesting, I like the decal idea.

**Comment by luciensadi** [comment]
Remaining work here is to double-check that dead inanimate NPCs don't add to the blood count.
