### ISSUE TITLE
Allow doors to be flagged as astrally warded to prevent astral exploration.

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#347]
Astral characters can essentially bypass all hidden exits by just walking through them. Enable astral warding such that a known warded door gives an error about a ward but an unknown warded door simply says you can't go that way.

**Comment by vitalyo7** [comment]
How are astral player supposed to open/pass through warded doors? Is this meant for specific high security zones or will this just punish the astral players for exploring?

**Comment by luciensadi** [comment]
There's no damage/punishment for a ward the way I'm envisioning it, it's just a block so that a mortal character is required to open the door before an astral can explore past it. It helps gate content so that they need the correct key etc to go deeper into the zone rather than making it so that a player with projection can bypass all the gating and see all the content at once.

**Comment by luciensadi** [comment]
Also yeah, it's more of a high-security thing. I wouldn't expect to see a ward on a random hideout unless it was a mage's place.
