### ISSUE TITLE
Add a verb for stance to automatically change dice pools during combat

### ISSUE THREAD

**Issue by vitalyo7** [luciensadi/AwakeMUD#368]
In order to simplify management of dice pools, a features is needed to automate the dice pool setting. This will likely help out newbies and experienced players.

Add command to allow player to set their combat stance
Add logic to combat rounds to recalculate dice allocation based on stance
Add display to score/informative commands to display dice pool due to stance

Allow the player to change combat stance from allout/aggressive/normal/defensive/manual that will allocate the combat dice pool automatically
allout 100/0
aggressive 75/25
normal 50/50 (default)
defensive 25/75
tank 0/100
manual (combat dice is not recalculated, player sets their own)

During each combat round, the dice should be recalculated automatically in case dice gets added/removed due to abilities/buffs/debuffs

When typing score/etc it should let the player know their current combat stance and dice pool allocation.

**Comment by luciensadi** [comment]
Manual doesn't need to be a specific stance, we can treat it like graphics settings in a game-- selecting a preset sets your values to that preset, but the moment you change anything it just reads 'Custom' for your preset.

```
> stance allout
You psyche yourself up for an all-out attack.

> pools
Combat: 10 (Dodge: 0 Body: 0 Offense: 10)

> cpool 2 3 5
Pools set as: Dodge-2 Body-3 Offense-5

> stance
You are currently in a custom stance.
```

How does the above mockup align with what you're thinking?

**Comment by vitalyo7** [comment]
That works
