### ISSUE TITLE
Ammunition overhaul

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#383]
The current bonding-magazines system is a step up from how the game used to behave, but it can still be improved. Instead of having players deal with obtaining and bonding magazines, just hand-wave it away.

1) All ammunition comes in boxes (like current setup).

2) To get ammunition from boxes, `LOAD <gun> [[FROM] <box>]`. This puts you in a short pause and creates a magazine for your gun from the ammo in the box. Ex:

```
> load ares
You gather some normal rounds from a box of standard pistol ammunition and slot them into a spare magazine for an Ares Predator III.

> i
You are carrying:
a box of standard pistol ammunition
a 15-round magazine of standard pistol ammunition
```

3) When you reload, change the message so that your character stows the magazine for later. Don't drop empty mags on the floor-- just extract them entirely.

```
> i
You are carrying:
Nothing.

> reload
You reload an Ares Predator III, stowing the empty mag for later.

> i
You are carrying:
Nothing.
```

Also, allow specification of ammo type in reload (`reload ares apds`) and have it select the proper magazine from your inventory.

**Comment by luciensadi** [comment]
See discussion in #329 for more information.

**Comment by vitalyo7** [comment]
I think ammo clips should only be used for display/shopping purposes. Once the player purchase a clip, it will automatically go to the default ammo container. The players can only carry ammo in an ammo container : ammo backpack, ammo belt etc. So when they go to a shop/dispenser, and purchase a clip they will not really get a clip, but the ammo automatically goes to the item storing the ammo. So the shopping interaction would be something like this.

If (they have a magazine container)
Your purchase 12 shotgun shells.
Your purchase 1 high-caliber magazine.

If not.
You need somewhere to store ammo chummer, equip an ammo backpack or something.

To see how much ammo they have, they would need to use look command or any informative commands on the ammo container or the weapon.

l ammo backpack
This is an olive green ammo backpack. It contains:
16 shotgun shells.
5 clips of ammo piercing rifle ammo.
5 arrows
1 poison dart

or 
look rifle
It is a generic rifle manufactured for mass consumption, that is likely to jam and get you killed.
It is currently loaded with regular ammo, containing 4 rounds out 16.
Your ammo backpack has 5 clips available.
Your ammo belt has 2 additional clips.

What do you think?

**Comment by luciensadi** [comment]
Yeah, I like that idea. It abstracts away a lot of the cruft while still keeping the "look at me, I've got bandoliers full of APDS" feel that players like.

We could keep the concept of ammo boxes, but make them less attractive compared to clothing. Maybe something like 'you can only reload in combat from your ammo clothing'? That'd also answer issues around inventory management where I might want to take ammo out of my clothes and replace it with other ammo-- just stick it in an ammo box and have done with it. Keeps gunsmithing ammo boxes relevant, too.
