### ISSUE TITLE
If staff attacks player, player gets KILLER flag from automatic counterattack.

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#39]
Hilarious, but I'm not sure if this is intended behavior. It doesn't seem worth designing around since the cases of staff attacking mortals will be rare to begin with and the staff probably won't care about a fair fight at that time.

**Comment by luciensadi** [comment]
Note: Mortal v mortal combat assigns killer properly.

**Comment by jalles76** [comment]
I'd say ignore it.
