### ISSUE TITLE
Missing skills?

### ISSUE THREAD

**Issue by jalles76** [luciensadi/AwakeMUD#4]
constants.cpp lists 133 skills, yet the DB has 135 skill rows.

the pfiles_skills table is regularly updated for immortal characters:

May 26 09:29:13 :: Executing query: DELETE FROM pfiles_skills WHERE idnum=1
May 26 09:29:13 :: Executing query: INSERT INTO pfiles_skills (idnum, skillnum, rank) VALUES (1, 1, 100), [...], (1, 134, 100), (1, 135, 100);

Hence we get two "empty" skills:

< 10P 10M > skills
You know the following skills:
[...]
Blowgun                         (godly)
Pharmacuticals                  (godly)
                                (godly)
                               (godly)

**Comment by luciensadi** [comment]
That one's on me, I added two slots for new skills I'm planning to put in (new languages). I'll decrement the MAX_SKILL define in awake.h until the new skills are officially in.
