### ISSUE TITLE
Unable to iload credsticks, but you can load them.

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#45]
I don't know why the iload restriction was put into place (my suspicion is that it's so an imm can't iload a credstick, put an arbitrary amount of nuyen on it, and hand it off to a mort without anyone tracking how much was given), but the restriction is not universal. It can be bypassed with LOAD OBJ <vnum>, or the imm could just buy a credstick from one of the vendors.

If the goal is to make it so imms Cannot Give Out Credsticks Ever, restrict them from doing so in give/drop.

Otherwise, just add logging so that the value of a credstick is displayed in the cheatlog and remove this restriction.

**Comment by jalles76** [comment]
Interesting. I'd say remove the restriction and log the amount.

**Comment by luciensadi** [comment]
I've set it up so that both `iload` and `load obj` share the same logic. I haven't removed the credstick load ban yet, mostly because I'm not sure why exactly it's there (cheatlog rationale aside). Will need further investigation, but I'll open a new issue for that.
