### ISSUE TITLE
Unexpected armor-overload warning on char with 0/0 armor and 1 qui

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#46]
A new character with 1 quickness and 0/0 armor got an armor-overload (encumbrance) warning when wearing a non-armored set of chains. This isn't the expected behavior unless any clothing encumbers a qui-1 char by canon.

**Comment by jalles76** [comment]
This looks like an oversight. I can't recall any such rule.

**Comment by luciensadi** [comment]
It was a code oversight; qui is an int, so qui * 3/4 was calculated as floor(qui*3/4), and when the check is 'if (0 >= 0)' then you're gonna get the warning message even though you have no armor.
