### ISSUE TITLE
'create ammo' item used is a beret

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#48]
It appears that item 121 (A UCAS Army Rangers Beret) is an ammo box in the base game; it's referenced by number in ammo creation, and you end up with a beret full of ammo at the end of it. While this is an entertaining mental image, either the item should be rewritten into an ammo container, or the vnum should be reassigned to something that is an ammo container, preferably between the 100-200 vnums.

**Comment by luciensadi** [comment]
Filed http://www.awakenedworlds.net/boards/viewtopic.php?p=9694#9694 to request the release of Zone 0.

**Comment by luciensadi** [comment]
Looking further at the forums, the last post that I can find by Che was in 2014, so it's possible he just doesn't check in there any more. Seems like the best way to resolve this is to just fix it ourselves and incorporate the new version of the area when/if it becomes available.

**Comment by jalles76** [comment]
Absolutely.
