### ISSUE TITLE
'info' with no arguments is overridden in shopkeeper's presence

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#49]
While standing in a room with a shopkeeper, 'info' with no arguments acts like 'info 1' rather than showing you the MUD info string. It should either display an error message telling you to select an item, or should display the MUD info string.

**Comment by jalles76** [comment]
Always display the info string if no argument is supplied would be my choice.

**Comment by luciensadi** [comment]
I've set it up so that 'info' with no arguments in the presence of a shopkeeper displays the syntax for the shopkeeper's info command. It makes it clear what the command is being used for at that point in time while also providing help for confused people.
