### ISSUE TITLE
gensql.sh not compatible with mysql < 5.7.8

### ISSUE THREAD

**Issue by jalles76** [luciensadi/AwakeMUD#53]
ERROR 1064 (42000) at line 2: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF EXISTS 'AwakeMUD'@'localhost'' at line 1

mysql> select @@version;
5.5.55-0ubuntu0.14.04.1

https://dev.mysql.com/doc/refman/5.7/en/drop-user.html
As of MySQL 5.7.8, the IF EXISTS clause can be used, which causes the statement to produce a warning for each named account that does not exist, rather than an error.

**Comment by luciensadi** [comment]
Fixed this issue in https://github.com/luciensadi/AwakeMUD/commit/0bb267fcd0eeb5c76dda025b222cfc6b78a7c25f. Please test and confirm.

**Comment by jalles76** [comment]
Tested and confirmed working.
