### ISSUE TITLE
Increased Reflexes spell incorrectly auto-failing due to attribute increasing Bioware

### ISSUE THREAD

**Issue by phosphor66** [luciensadi/AwakeMUD#530]
**Describe the bug**

Recently got a Cerebral Booster II installed on my full-mage character (Volund). Now, I auto-fail every attempt to cast Increased Reflexes 3 on self. 

**To Reproduce**
1. Create a mage character with access to Increased Reflexes spell.
2. Purchase Cerebral Booster II on mage character.
3. Cast Increased Reflexes on self.
4. Auto-fail casting, every time.

**Expected behavior**
Spell should still be applicable despite the augmentation from bioware. See the Additional context section below for details.

**Current Output**
"You fail to bind the mana to your will."

**Additional context**

This issue is likely due to interpretation of an ambiguous spell description in the SR3 main book...

_SR3 pg. 194, Increased Reflexes Spell says..._
>  ...characters that have cybernetic enhancements that add Reaction or Initiative dice (like wired reflexes) cannot be boosted by this spell.

This ambiguous passage is the likely origin of this bug. It can be easily interpreted to include ware that increases Qui or Int, since those can potentially increase Reaction as a secondary effect. Given the specific mention of wired reflexes as an example the likely spirit of the rule is to prevent initiative dice stacking (e.g. wired reflexes and increased reflexes spell).

Man & Machine provides more clarification on the impact of attribute increasing bioware...

_MM pg. 77, Natural or Augmented says..._
>  Because bioware is created to match the user's physiology, any Attribute bonuses conferred by bioware are treated as natural and unaugmented. In other words, they count as changes to the character's base Attributes.

Since bioware attribute increases should be calculated as part of the base or unaugmented stats, they should not prevent the application of the Increased Reflexes spell.

*At it's core, the change needed is to treat bioware attribute increases as natural in code.*

**Other potential impact**

Fixing this will likely have further ranging impact than just the Cerebral Booster/Increased Reflexes spell interaction.  

- Some things to consider when treating bioware attribute increases as natural:
  - Increase (Cybered Attribute) should no longer be required for attributes with bioware only augmentation, Increase (Attribute) should be used instead.
  - Need to consider impact on attribute maximums since this would potentially allow exceeding them, depending on implementation.
  - Adept stuff...I'm not all that familiar with adepts but I'm sure this would probably impact several of their abilities.
- Any potential impacts on attribute training system I don't know about.

**Comment by luciensadi** [comment]
Agreed that this change needs to be made, but it will take some work to make it happen. All attribute changes are currently lumped together into one value, so the code will need to be changed to call out which modifications are bioware-related and which are not. In the meantime, I'll update the error message for this failed cast to explicitly state the error case.
