### ISSUE TITLE
'tail' command currently broken

### ISSUE THREAD

**Issue by jalles76** [luciensadi/AwakeMUD#55]
ACMD(do_tail) uses two system calls (ls, tail) to list available logs and tail them. As log/ doesn't exist the command does nothing at the moment. I'm not sure I like passing commands to a shell from the game. However, it'd be nice for a staffer without shell access to view and/or search logs.

**Comment by luciensadi** [comment]
Added log/ directory to main repo and sanitized do_tail to only accept letters, numbers, and periods.
