### ISSUE TITLE
Adding elevators/vehicle shops to cloned repo (how's the best way?)

### ISSUE THREAD

**Issue by celtichawk** [luciensadi/AwakeMUD#571]
So, got this running on a small LAn for a writing group who love Shadowrun and figured okay. I'll give this a whirl and se how they like it.

But we ran into an issue. That is....how do we add the missing elevators/vehicle shops around the rooms? I'm trying to ad in the missing elevators because one of the group is stuck after renting at the Homewood Suites and not being able to get to their apartment without being teleported, and I'm unable to find the docs on adding elevators. I tried adding the rooms in the /etc/elevators file and it just resulted in the normal termination of game in the log and in a restart loop,

So. Is there a step by step guide for adding in elevators?

And related 'how do I add things for my group' query. Vehicle shops. I'd like to give my folks somewhere to get vehicles that isn't the buy from admin HQ and set vehicle owner stuff. So how would I, from a freshly cloned repo, achieve both these things. Or is there a file in the repo with all the elevators already set in the built areas or a doc on this I've missed somewhere?

**Comment by celtichawk** [comment]
Okay found the docs. Is there a way to add the elevators while logged in as an admin. I'm unsure so figured I'd ask, it's a bit off putting to the group that they can't get to use stuff they've paid for in game or have to be teleported everywhere, so not sure if there's an easier way to add in the elevators from within the game or not. I'm going off of a bone stock repo for the group for reference

**Comment by luciensadi** [comment]
The elevators have to be written as a flat file on disk (`lib/etc/elevator`), and they're only installed on copyover. At this point the repo world has diverged pretty significantly from the game world, so while I can provide [the elevator file we're using in CE](https://pastebin.com/9bQ5cKnv), it may not be of much use. Let me know if it works for you.

**Comment by celtichawk** [comment]
I'll try that, I was thrown by the readme saying to only have one vnum, and the examples in the file having multiple ones not covered. Is there anywhere that difference is addressed in the help docs or is it just the readme in /etc that goes over it?

**Comment by luciensadi** [comment]
Vehicle shops are done by assigning a mob the `car_dealer` spec-proc and sticking them in a room. It uses the room with the vnum directly before your dealer's room as the car storage lot, so set zoneloads for all the vehicles you want for sale and have them load in that lot (which should be closed off and inaccessible from the game). The car_dealer mob will sell copies of any vehicle in that lot.

Here's how it looks at Crazy Lenny's in game:
```
> at 1398 l
[ 1398] Car Dealer Storage Room [  ]
   This room is to store the cars that car dealer would sell, until I can
write a proper shop type system for them. wizload or zoneload any vehicles you
want sold in here. 
Obvious exits:
 None.
Rain splashes into the puddles around your feet.
A three-wheeled, single-passenger commuter car is parked here.
A well-engineered sport utility vehicle is parked here.
A full-sized luxury car is parked here at a curb.
A Honda Viking motorcycle is parked here.
A high-performance motorcycle is parked here.
A Harley-Davidson Scorpion sits here.
A Dodge Scoot is parked here.
A Ford Americar sits here stoutly, parked at a curb.
A sleek, stylish Eurocar Westwind 2000 is parked here.
A Chrysler-Nissan Jackrabbit-E sits silently here.

<10P 10M> 
> at 1399 l
[ 1399] Crazy Lenny's Crazy Deals [ !MOB, STREETLIGHTS, GARAGE ]
   You are surrounded by a great number of cars, lining the whole lot from
front to back, of more makes and models than most would ever dream. Ford.
Isuzu. Mitsubishi. Dodge. Toyota. Aztechnology. It's all there, and it's all
for sale-- and if you believe the proprietor, they're all crazy deals. 
Obvious exits:
South - [32670] Espanoza Way
Rain splashes into the puddles around your feet.
...There are vehicles for sale here.
A crazily-grinning ork in a plaid zoot-suit is walking up and down the lot. 
```

**Comment by luciensadi** [comment]
Readme hasn't been updated recently. There are now two vnums: one for the floor's exit, and one for the shaft room that covers that floor.

**Comment by celtichawk** [comment]
Okay no that didn't work. I just get normal termination of game, with no other errors using the linked file. If I follow the example with the readme, same deal with a normal termination of game as well and a restart loop. Do I need to do anything specific after pasting the file in?

**Comment by luciensadi** [comment]
Can you pastebin your complete startup log?

**Comment by celtichawk** [comment]
Ah I can try grabbing the startup log or console output, if I know where the output is.

So from scratch it'd be:

1. Go to, let's use the Homewood Suites as an example
2. Dig the shaft rooms
3. 3. Put the floor num, shaft vnum and exit dir in the elevators file

And that should work?

I'll pastebin the console output but once I hit autorun it restarts until the task is killedd, and like I said I've no clue where the log files are at however

**Comment by luciensadi** [comment]
The autorun version saves them to the game's log/ directory, but while testing I usually just do `gdb bin/awake` from the game's root directory.

**Comment by celtichawk** [comment]
I've got things to work...sort of. I'm running into an issue I didn't see documented on the wiki.

Which is. The floors are inverted. I've got it set up correctly, all the floors are there. But no matter what I change....it treats the top floor as the ground floor. So it descends when going to higher floors, and ascends to lower floors. Does the order of the vnums matter or not? I've not seen it at all in the file anywhere else.

I have the vnums in ascending order with the shafts. For example

12345 45678 4
12346 45678 4
13346 45678 4

And in that example. It should treat the first line as the ground floor and ascend  through the lines.

So in the example. I'd enter the elevator at the first one and hit 3 to go to the third one. Instead of ascending, the elevator descends. Is that because somehow I've set it up wrong, or is it down to the zone in question I was using? Again it's not covered in the wiki and I'm not sure if I did something wrong putting the lines in that order

**Comment by luciensadi** [comment]
I'm actually surprised it didn't break completely with that elevator file snippet you posted; you're using the same room for all the shaft rooms and you've duplicated a floor.

The elevator file is organized like the building, with the top of the file being the top of the floor and subsequent floors going down from there. Ex:

```
60531 1 2 4
60530 60655 4
60532 60656 4
```

```
[60531] Inside the Neophyte Elevator [ INDOORS, PEACEFUL, !RADIO, !BIKE ]
...
Obvious exits:
South - [60530] Operating Elevators
...
The floor indicator shows that the elevator is currently at floor 5.
```
