### ISSUE TITLE
Cleaning up racist spec_proc

### ISSUE THREAD

**Issue by UndeadNappist** [luciensadi/AwakeMUD#589]
Came up for racist bouncers or whatever, but it would be nice to have more specprocs merged into the standard build menu and not have to build unique ones every time we want to get something done.

Discussion was around racism

racism(bouncer/mob/questor, whatraces/!whatraces, "Unique dialogue"), something like that. Fewer lines of code to do in the future, as well.

Could even go a step further and add a chat command and make random lines of dialogue NPCs sprout only occur when you CHAT with them. More implementation into the build menu maybe?

**Comment by GarbageJet** [comment]
Also would be really nice to include other criteria like mage, ware, etc.
