### ISSUE TITLE
Error in damage calculation of matrix fights

### ISSUE THREAD

**Issue by gabrielbalogh** [luciensadi/AwakeMUD#618]
Hi,

I'm playing the game on my local clone and noticed that matrix fights felt too difficult. After some old fasion code reading I found this line of code in the newmatrix.cpp file:
at 522-ish:
    `  dam = MAX(matrix[icon->in_host].colour + 1, DEADLY);`
I don't want to include more lines, but this is where the damage level (L,M,S,D) is calculated for ic attacks. 
I think the developer's original intention was to give an upper limit  of "DEADLY(4)" for damage level  to not to "overflow" the constant. But instead his/her inner devil managed to sway it that way that every ic got Deadly damage regardless of the host security level due this line of code.

I've replaced the MAX function with  the MIN function
     ` dam = MIN(matrix[icon->in_host].colour + 1, DEADLY);`
 and it  works better now for me and also comply better to SR rules too.
Playing a decker character at the newbie level is very difficult so if you fix this in the community edition I am sure it will be well received :-)

Thanks for all the contributors to their hard work!

Take care,
a humble chummer

**Comment by luciensadi** [comment]
Hah, great find! Thanks for bringing it to my attention.
