### ISSUE TITLE
Looks like calculate_vehicle_weight was missed in portabikes commit

### ISSUE THREAD

**Issue by psulliv** [luciensadi/AwakeMUD#621]
We are trying to link `calculate_vehicle_weight()` in `src/act.obj.cpp` from efcc2b594768fa3044513a1faf5cf43b3b29472a but it isn't in `src/act.drive.cpp` as of b10f0d81a48d60c02618411e969ed86789310671

results in: 
```
src/act.obj.cpp:1184: undefined reference to `calculate_vehicle_weight(veh_data*)'
```

I'm thinking that the implementation in https://github.com/luciensadi/AwakeMUD/pull/596 is what it was supposed to look like but i just subbed in a function that returns 0 and it builds at least.

**Comment by luciensadi** [comment]
Yeah, I cribbed the function from that PR and put it in a non-checked-in file on my port because the function is useful, but I was thinking that PR would be in by now. I'll add the function to the official repo.

**Comment by luciensadi** [comment]
Added in 62fb25ef68cdb7906e6fb5bb6a148395a6ed33bc. Thanks for the report!
