### ISSUE TITLE
Ordering spirits crashes the game

### ISSUE THREAD

**Issue by celtichawk** [luciensadi/AwakeMUD#624]
I'm not sure which commit introduced this since i've not touched the version on my server for a while, but as of a few days ago one of my shaman players mentioned this to me so I managed to repro it.

Ordering a spirit to attack (not sure on elementals) crashes the game with the following:

==57076==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000010df998 at pc 0x000000bbe990 bp 0x7ffd5e692f10 sp 0x7ffd5e692f08
READ of size 1 at 0x0000010df998 thread T0
    #0 0xbbe98f in is_abbrev(char const*, char const*) /home/vagrant/awakemud/src/interpreter.cpp:2051:18
    #1 0x69c36e in impl_do_order_(char_data*, char*, int, int) /home/vagrant/awakemud/src/newmagic.cpp:4775:11
    #2 0x69b59f in do_order(char_data*, char*, int, int) /home/vagrant/awakemud/src/newmagic.cpp:4694:1
    #3 0xbb3ac0 in command_interpreter(char_data*, char*, char*) /home/vagrant/awakemud/src/interpreter.cpp:1668:8
    #4 0x578831 in game_loop(int) /home/vagrant/awakemud/src/comm.cpp:816:13
    #5 0x56f93c in init_game(int) /home/vagrant/awakemud/src/comm.cpp:434:3
    #6 0x56f88e in main /home/vagrant/awakemud/src/comm.cpp:263:5
    #7 0x7f3fb87980b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #8 0x420bed in _start (/home/vagrant/awakemud/bin/awake+0x420bed)

0x0000010df998 is located 0 bytes to the right of global variable 'services' defined in 'newmagic.cpp:4668:19' (0x10df440) of size 1368
SUMMARY: AddressSanitizer: global-buffer-overflow /home/vagrant/awakemud/src/interpreter.cpp:2051:18 in is_abbrev(char const*, char const*)
Shadow bytes around the buggy address:
  0x000080213ee0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080213ef0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080213f00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080213f10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080213f20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x000080213f30: 00 00 00[f9]f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x000080213f40: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x000080213f50: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x000080213f60: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x000080213f70: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x000080213f80: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc

My VPS is running Ubuntu 20.04.5 compiled with the instructions from the README file, the sole change being using Maria-DB instead of MySQL

I'm trying to work out which commit introduced this into the public repo but not having much luck however

**Comment by luciensadi** [comment]
Thanks for reporting this! This was caused by me commenting out unused services without realizing that I needed to also change the way it looked for services. I've removed my comment-out for now, this should no longer crash.
