### ISSUE TITLE
Missing gear in chargen

### ISSUE THREAD

**Issue by jalles76** [luciensadi/AwakeMUD#63]
- pocketsec (discussable, of course)
- survival gear vendor only offer trauma patches
- Missing completely: armor/clothing vendor
- melee vendor has a very sparse supply
- firearms vendor has a very sparse supply / room description does not fit stock
- ammo shop needs update (substitute magazines with generic ones)
- talismonger doesn't have enough variety and is lacking enchanting mats and libraries

**Comment by luciensadi** [comment]
Re: pocket secretaries, it'll need to be examined to ensure there's no way to ship nuyen out of chargen. I believe there's an ATM in chargen (to be verified)-- we should also verify that the wire command can't be used from the ATM either.

**Comment by jalles76** [comment]
Good thinking. It never occured to me that this could be the reason they're not present. Not sure about Che's server but I seem to recall you can't buy them in chargen there either. As for the ATM in chargen, I never noticed one. Probably less of a hassle to just make these items not available.

**Comment by luciensadi** [comment]
Fixed in import.
