### ISSUE TITLE
Update INFO command

### ISSUE THREAD

**Issue by jalles76** [luciensadi/AwakeMUD#64]
see issue #62. Output from INFO should be generic.

**Comment by jalles76** [comment]
Added file info-ng to txt/ of devport. Generic $MUDNAME used for all references to the mud's name.

**Comment by jalles76** [comment]
No need to change it atm

**Comment by luciensadi** [comment]
Need to change 'Awakened Worlds' references to 'Awake CE' or similar to avoid stepping on Awake Classic's toes.
