### ISSUE TITLE
Tell new players they'll get a new radio before spending money on one

### ISSUE THREAD

**Issue by jalles76** [luciensadi/AwakeMUD#66]
Players should be warned not to spend money on a radio in chargen.

**Comment by luciensadi** [comment]
It might be better to just give them the activated radio from the start and have the chargen rooms be !RADIO. That way it's clear they have it and don't need another, but they're not getting messages they can't handle.

**Comment by jalles76** [comment]
Good idea. I wonder what's the best way to implement this. I guess we could just use the code handing out the Seattle map and tell them in the room describing radio usage (if that room is before the gear vendors).

**Comment by luciensadi** [comment]
This was resolved in PR #82.
