### ISSUE TITLE
Let players choose their first language for free in chargen

### ISSUE THREAD

**Issue by jalles76** [luciensadi/AwakeMUD#67]
Players should have the freedom to choose their first language. Check canon rules on that. Skill level could be INT+2 or 3 if no rules exist.

Players need to be warned of difficulties in communicating with other players ICly.

**Comment by luciensadi** [comment]
This will be in the 0.9.0 roadmap. I'm thinking that the criteria for this issue are:

- your first language is max skill (failing to speak isn't fun in the current system)
- if your first language is not English, warn player

**Comment by luciensadi** [comment]
Implemented. You can untrain your language in Chargen.
