### ISSUE TITLE
In-Game Bug Report: Vehicles don't play well with ch->in_room checks. Several cra...

### ISSUE THREAD

**Issue by AwakeMUD** [luciensadi/AwakeMUD#76]
...shes have been exposed just by sitting in a vehicle and performing various commands. It would be prudent to search for all calls to world[ch->in_room] and other in_room variables and verify that the room is not NOWHERE before we execute.

Filed by Lucien (id #1) from the rear of a vehicle of vnum 1309, located in room 10000.

**Comment by luciensadi** [comment]
The more I look at it, the thornier this problem gets. `world[ch->in_room]` is a pervasive coding pattern, and the 'fix' I see in places (`world[ch->in_veh ? ch->in_veh->in_room : ch->in_room]`) also fails if the character is inside a vehicle that is inside another vehicle. The real fix for this appears to be implementing a method that fetches the in_room of the character and handles the logical edge cases, but subsequently swapping out all calls to in_room with this is a daunting task.

**Comment by jalles76** [comment]
Indeed. 327 occurences of ````world[ch->in_room]````

**Comment by luciensadi** [comment]
Closing this issue and branch in favor of #148 and `issue-148` respectively. Plenty of work remains, but the new function is much more readable than the old one in the `in-room` branch.
